reviews:
  auto_review:
    enabled: true
  review_level: detailed     # brief | detailed
  max_comments: 30           # 과도한 코멘트 방지

  focus_areas:
    - architecture
    - domain_modeling
    - performance
    - security
    - test_coverage

  ignore_files:
    - "**/build/**"
    - "**/generated/**"
    - "**/*.md"
    - "**/Q*"
    - "**/resources/static/**"

comments:
  style: actionable
  language: ko
  tone: constructive

rules:
  - name: "Controller 책임 침범 감지"
    description: "Controller에 비즈니스 로직이 포함되는 경우"
    pattern: "Controller"
    suggestion: >
      Controller는 요청/응답 변환만 담당하는 것이 좋습니다.
      비즈니스 로직은 Service 또는 Domain Layer로 이동하는 것을 고려해보세요.

  - name: "도메인 로직 외부 노출 감지"
    description: "엔티티가 setter 중심으로 상태를 변경하는 경우"
    pattern: "set[A-Z]"
    suggestion: >
      상태 변경 로직을 의미 있는 도메인 메서드로 캡슐화하면
      설계 의도와 불변성을 더 잘 표현할 수 있습니다.

  - name: "트랜잭션 경계 점검"
    description: "@Transactional 범위가 과도한 경우"
    pattern: "@Transactional"
    suggestion: >
      조회 전용 로직에는 readOnly = true 설정 또는
      트랜잭션 분리를 통해 의도를 명확히 하는 것이 좋습니다.

  - name: "조회 설계 확장성 점검"
    description: "조건이 많은 findBy 메서드 감지"
    pattern: "find.*By.*And.*And"
    suggestion: >
      조건 확장이 예상되는 조회는 QueryDSL 전용 Repository로 분리하면
      유지보수성과 성능 측면에서 유리할 수 있습니다.

  - name: "설계 의미 있는 코드의 테스트 권장"
    description: "Policy / Guard / 핵심 Service 테스트 여부"
    pattern: "Policy|Guard|Service"
    suggestion: >
      설계 의미가 있는 로직은 테스트를 통해
      선택의 의도를 고정하는 것이 좋습니다.

tests:
  require_tests_for:
    - "**/*Service.java"
    - "**/*Policy.java"
    - "**/*Guard.java"