reviews:
  auto_review:
    enabled: true
  profile: assertive

  path_filters:
    - "!**/build/**"
    - "!**/generated/**"
    - "!**/*.md"
    - "!**/resources/static/**"

  path_instructions:
    - path: "**/*Controller*.java"
      instructions: >
        Review controllers to ensure they only handle request/response mapping.
        Business logic should be placed in Service or Domain layers.

    - path: "**/*Service*.java"
      instructions: >
        Focus on responsibility boundaries, transactional scope,
        and whether business rules belong in the domain.

    - path: "**/*Policy*.java"
      instructions: >
        Treat policies as design-critical code.
        Verify that logic is explicit and testable.

    - path: "**/*Repository*.java"
      instructions: >
        Watch for query complexity and potential scalability issues.
        Suggest QueryDSL when query conditions may grow.

ai:
  instructions: |
    All review comments must be written in Korean.
    Focus on design intent, responsibility boundaries, and domain modeling.
    Treat tests as documentation of design decisions, not mere coverage.
    Prefer constructive suggestions over commands.
    Do not comment on formatting or naming style.
