spring:
  datasource:
    url: ${DB_URL}?reWriteBatchedInserts=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        jdbc:
          batch_size: 500
        order_inserts: true
        order_updates: true
        generate_statistics: false

  flyway:
    schemas: public
    locations: classpath:db/migration
    out-of-order: false
    baseline-on-migrate: false
    lock-retry-count: 10

  lifecycle:
    timeout-per-shutdown-phase: 30s

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  task:
    scheduling:
      enabled: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  elasticsearch:
    uris: ${ES_URI}
    connection-timeout: 3s
    socket-timeout: 5s

jwt:
  secret: ${JWT_SECRET}
  tokens:
    ACCESS:
      expiration: ${JWT_ACCESS_EXPIRATION}
    REFRESH:
      expiration: ${JWT_REFRESH_EXPIRATION}
    SIGNUP:
      expiration: ${JWT_SIGNUP_EXPIRATION}

logging:
  level:
    org.hibernate.SQL: off
    org.hibernate.type: off

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics, loggers, flyway, caches
  endpoint:
    health:
      probes:
        enabled: true
      show-details: when_authorized
      group:
        liveness:
          include: livenessState, diskSpace
        readiness:
          include: readinessState, db, redis
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5, 0.95, 0.99
    tags:
      application: nuda-server
      environment: prod


cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET}
    cloudfront:
      domain: ${CDN_DOMAIN}

server:
  shutdown: graceful
  tomcat:
    connection-timeout: 120000
    max-swallow-size: 100MB

ml:
  base-url: ${ML_BASE_URL}
  connect-timeout: 2000
  read-timeout: 5000

resilience4j:
  retry:
    instances:
      es-sync:
        max-attempts: 3
        wait-duration: 10s
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2