-- ENUM
CREATE TYPE member_role AS ENUM ('USER', 'ADMIN');
CREATE TYPE member_status AS ENUM ('ACTIVE', 'INACTIVATE');
CREATE TYPE irritation_level AS ENUM ('NONE', 'SOMETIMES', 'OFTEN');
CREATE TYPE scent_level AS ENUM ('NONE', 'MILD', 'STRONG');
CREATE TYPE change_frequency AS ENUM ('LOW', 'MEDIUM', 'HIGH');
CREATE TYPE thickness_level AS ENUM ('THIN', 'NORMAL', 'THICK');
CREATE TYPE priority_type AS ENUM ('SAFETY', 'ABSORPTION', 'SOFTNESS');
CREATE TYPE product_category AS ENUM (
    'LINERS', 'REGULAR', 'HEAVY', 'OVERNIGHT', 'TEMPO'
);
CREATE TYPE image_type AS ENUM ('MAIN', 'DETAIL');


-- FUNCTIONS
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
RETURN NEW;
END;
$$ LANGUAGE plpgsql;